<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')) :
    $activeTabPosition = 0;
    $layout = $block->getLayout();

    // Check if $detailedInfoGroup has testimonials and set this tab active if it has
    foreach ($detailedInfoGroup as $index => $name) {
        if (strpos($name, 'testimonial') !== false && $layout->renderElement($name) !== '') {
            $activeTabPosition = $index;
            break;
        }
    }
    ?>
    <div class="product info detailed">
        <div class="product data items" data-mage-init='{"tabs":{"active":<?= $activeTabPosition; ?>,
        "openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $index => $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content" <?php if ($alias === 'testimonials') {
                    echo /* @escapeNotVerified */ "data-mage-init='{\"testimonials\":{}}'";
                }?> >
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
