<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')) :
    $activeTabPosition = 0;
    $carouselCondition= false;
    $testimonials = 0;
    $layout = $block->getLayout();
    $data = [];
    // Check if $detailedInfoGroup has testimonials and set this tab active if it has
    foreach ($detailedInfoGroup as $index => $name) {
        if (strpos($name, 'testimonial') !== false && $layout->renderElement($name) !== '') {
            $activeTabPosition = $index;
            $carouselCondition = true;
            break;
        }
    }
    ?>
    <div class="product info detailed">
        <div class="product data items" data-mage-init='{"tabs":{"active":<?= $activeTabPosition; ?>,
        "openedState":"active"}}'>
            <?php foreach ($detailedInfoGroup as $index => $name) :?>
                <?php
                $html = $layout->renderElement($name);
                if (!trim($html)) {
                    continue;
                }
                $alias = $layout->getElementAlias($name);
                $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?= /* @escapeNotVerified */ $alias ?>"
                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                        <?= /* @escapeNotVerified */ $label ?>
                    </a>
                </div>
                <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                    <?= /* @escapeNotVerified */ $html ?>
                </div>
            <?php $data[$index] = $html;
            endforeach;

            $data = [[0], [5]];

if ($carouselCondition === true) : ?>
<script type="text/x-magento-init">
    {
        "#testimonials": {
            "mage/gallery/gallery": {
                "data": [
                {
                    "image"  : "",
                    "caption": "<?= "sdf"?>",
                    "isMain" : true
                },
                {
                    "image"  : "",
                    "caption": "sghsghfhd"
                }
                ],
                "options": {
                    "allowfullscreen"   : false,
                    "maxheight"         : "100",
                    "nav"               : "dots",
                    "loop"              : true,
                    "keyboard"          : false,
                    "arrows"            : true,
                    "showCaption"       : true,
                    "transitionduration": 500,
                    "transition"        : "slide",
                    "navarrows"         : false,
                    "navtype"           : "slides",
                    "navdir"            : "horizontal"
                },
                "fullscreen": {
                },
                "breakpoints": {
                    "mobile": {
                        "conditions": {
                            "max-width": "767px"
                        },
                        "options": {
                            "options": {
                                "nav":"dots"
                            }
                        }
                    }
                }
            }
        }
    }
</script>

<?php endif; ?>

        </div>
    </div>
<?php endif; ?>
