<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php

    if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):

        // Check if $detailedInfoGroup has testimonials and set this tab active if it has
        foreach ($detailedInfoGroup as $name) {
            if (strpos($name, 'testimonial')) {
                $activeTabPosition = count($detailedInfoGroup) -1;
            } else $activeTabPosition = 0;
        }
        ?>

        <div class="product info detailed">
            <?php $layout = $block->getLayout(); ?>
            <div class="product data items" data-mage-init='{"tabs":{   "active":<?= $activeTabPosition; ?>,
                                                                    "openedState":"active"}}'>
                <?php foreach ($detailedInfoGroup as $name):?>
                    <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');

                    if ($label === 'Testimonials') {
                        $activeTabPosition = 3;
                    }

                    ?>
                    <div class="data item title"
                         aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
                         data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
                        <a class="data switch"
                            tabindex="-1"
                            data-toggle="switch"
                            href="#<?= /* @escapeNotVerified */ $alias ?>"
                            id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
                            <?= /* @escapeNotVerified */ $label ?>
                        </a>
                    </div>

                    <div class="data item content" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
                        <?= /* @escapeNotVerified */ $html ?>
                    </div>

                <?php endforeach;?>
            </div>
        </div>
<?php endif; ?>
