<?php /* @var $block \Stanislavz\CurrentCategory\Block\Visited\Categories\Sidebar */ ?>
<div class="block block-visited-categories" data-bind="scope: 'visitedCategoriesSection'">
    <div class="block-title">
        <strong id="block-visited-categories-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ __('Visited Categories') ?></strong>
    </div>
    <div class="content">
        <ul class="custom-category-crumb-list" data-bind="foreach: { data: visitedCategoriesSection().items, as: 'item'}">
            <li>
                <ul class="custom-category-crumbs">
                    <!-- ko foreach: parent_categories -->
                    <li>
                        <a data-bind="attr: { href: $data.parent_categories_url }, text: $data.parent_categories_name"></a>
                    </li>
                    <!-- /ko -->
                    <li>
                        <a data-bind="attr: { href: item.category_url}, text: category_name"></a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".block-visited-categories": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
        }
    }
</script>