<?php
/** @var \Stanislavz\CurrentCategory\Block\RecentlyVisitedCategories $block */
if ($block->pagePreloader->isCustomerLoggedIn()) :
    $categoriesCollection = $block->getRecentlyVisitedCategories();
?>
<ul class="custom-category-crumb-list">
    <?php foreach ($categoriesCollection as $category) : ?>
    <li>
        <ul class="custom-category-crumbs">
            <?php foreach ($category->getParentCategoriesList() as $parentCategory) : ?>
                <li>
                    <a href="<?= $parentCategory->getUrl(); ?>"><?= $parentCategory->getName(); ?></a>
                </li>
            <?php endforeach; ?>
            <li>
                <a href="<?= $category->getUrl(); ?>"><?= $category->getName(); ?></a>
            </li>
        </ul>
    </li>
    <?php endforeach; ?>
</ul>
<?php else : ?>
<div class="custom-category-crumb-list">
    <script type="text/x-magento-init">
    {
        ".custom-category-crumb-list": {
            "visitedCategories": {
                "categoryId" : "<?= $block->pagePreloader->getCurrentCategory()->getId(); ?>",
                "limit"      : "<?= $block->getLimit(); ?>"
            }
        }
    }
    </script>
</div>

<?php endif; ?>
